<i18n>
    {
    "en": {

    "page-title": "Privacy Policy & Terms of use",

    "terms-heading": "Terms of Use",

    "terms-list-intro": "In these Terms of Use we define:",
    "terms-list-item-1": "<b>CCCS</b> as the Competence Center Citizen Science (usually referred to as Citizen Science Center Zurich).",
    "terms-list-item-2": "<b>CS Zurich platforms</b> as including the citizenscience.ch platform and all related project platforms (named, for any project “xxx” as “xxx.citizenscience.ch”).",
    "terms-list-item-3": "<b>Users</b> as any visitor on the CS Zurich platforms.",
    "terms-list-item-4": "<b>Project Creators</b> as the users that initiate and manage a project, including defining the project’s content (in any form), providing the necessary data (in any form), and recruiting other users to contribute to their project in the manners allowed by the functionalities of the platforms. Project Creators do not include employees of the CCCS.",
    "terms-list-item-5": "<b>Contributors</b> as the users that voluntarily contribute to projects in the manners allowed by the functionalities of the platforms. Contributors can be anonymous or choose to voluntarily provide some personal information by registering to the CS Zurich platforms.",

    "terms-text-1": "The following Terms of Use apply to all users visiting and/or using in any manner the <b>CS Zurich platforms</b>.",
    "terms-text-2": "<b>Project Creators</b> are wholly responsible for fulfilling obligations related to any project they create and any form of data they upload. They agree to obtain copyrights permissions and, in case of copyright infringement, they are liable to pay damages to the copyright owner",
    "terms-text-3": "<b>Contributors</b> are the owner of their own contributions and are responsible for such ownership. If they are not the content owner, they must have permission from the owner prior to contributing.",
    "terms-text-4": "<b>Contributors</b> grant the <b>CCCS</b> a perpetual, royalty-free, non-exclusive license to use, reproduce, modify, and exercise all copyright and publicity rights with respect to their contribution.",
    "terms-text-5": "Contributions to the CS Zurich platforms are available to the Project Creators with a non-exclusive permission to use, distribute, and modify in order to further scientific research.",
    "terms-text-6": "<b>CCCS</b> does not have any ownership rights in the content that <b>Project Creators</b> upload to the <b>CS Zurich platforms</b>. <b>CCCS</b> cannot be held accountable of privacy, legal, or other forms of responsibilities related to data uploaded by <b>Project Creators</b> in the <b>CS Zurich platforms</b>.",
    "terms-text-7": "In the event of a dispute between <b>Project Creators</b> and <b>Contributors</b>, the <b>CCCS</b> is released from claims of every kind and in any way related to such dispute.",
    "terms-text-8": "<b>CCCS</b> does not endorse and has no control over any contribution, cannot guarantee the authenticity of any data which users may provide, and makes no guarantees regarding the performance or fairness of contributors’ activities.",
    "terms-text-9": "With particular reference to the Citizen Science Project Builder ({lab}) CCCS reserves the right to remove content and projects where the content is not legal or deemed likely to cause offense to some audience.",

    "research-heading":"Research Data Policy",
    "research-text-1":"Data generated by the projects hosted in the CS Zurich Platforms follows the EC recommendations of the FAIR Data Management Plan defined as '{link-research}', which focuses on encouraging as few restrictions as possible, while at the same time protecting sensitive data from inappropriate access.",
    "research-text-2":"<b>CCCS</b> should be acknowledged in any publications with the text: 'This publication uses data generated via the citizenscience.ch platform of the Citizen Science Center Zurich, a joint initiative of the University of Zurich and ETH Zurich'. ",

    "privacy-heading": "Privacy Policy",

    "privacy-text-1": "All data are submitted in accordance with the Swiss Data Protection Act ( DSG ) and the EU General Data Protection Regulation ( GDPR ). All data are stored in servers within Switzerland.",
    "privacy-text-2": "At registration in the platform, <b>users</b> may choose to provide an e-mail address (registration). This e-mail address is not visible, and <b>CCCS</b> will never share email adresses, or personal details, outside of the projects a user has given explicit permission to.",
    "privacy-text-3": "<b>CCCS</b> will use users’ email address only occasionally, to announce new features, new projects, or special events. CCCS may contact users with a newsletter about the progress of the project or the activities of the Center. Users can opt-out of such communications at any time.",
    "privacy-text-4": "<b>CCCS</b> aggregates general statistics on the use of CS Zurich platforms. For this, <b>CCCS</b> uses Google Analytics, a software that collects data associated with the user’s IP address. The information collected by Google Analytics is treated according to their {policy}.",
    "privacy-text-5": "Temporary cookies may be used when individual CCCS pages are accessed. Temporary cookies are small files that the page stores on your computer to enable optimal use of the website; the cookies are deleted automatically when the web browser is closed. You can block the use of temporary cookies by adjusting the relevant settings in your web browser. Please note that disabling, blocking, or deactivating cookies can limit the functionality of the CCCS web pages.",

    "help-text-1":"For further questions on the use of data, please contact CCCS at the following address:",
    "help-text-2":"Citizen Science Center Zurich",
    "help-text-3":"Kurvenstrasse 17",
    "help-text-4":"CH-8006 Zurich"

    },
    "de": {


    "page-title": "Privacy Policy & Terms of use",

    "terms-heading": "NUTZUNGSBEDINGUNGEN",

    "terms-list-intro": "Die in diesen Nutzungsbedingungen verwendeten Begriffe und Abkürzungen haben die folgende Bedeutung:",
    "terms-list-item-1": "<b>CCCS</b>: Competence Center Citizen Science (üblicherweise als Citizen Science Center Zürich bezeichnet)",
    "terms-list-item-2": "Plattformen von CS Zürich: Hierzu gehören die Plattform «citizenscience.ch» sowie alle damit verbundenen Projektplattformen (deren Namen je «xxx.citizenscience.ch» lauten, wobei «xxx» für das jeweilige Projekt steht)",
    "terms-list-item-3": "<b>Nutzende Personen</b> : alle Besucherinnen und Besucher der Plattformen von CS Zurich.",
    "terms-list-item-4": "<b>Projektentwickelnde Personen</b>: Nutzende Personen, die ein Projekt erstmalig anlegen, verwalten, die Projektinhalte definieren (in jeder Form), die erforderlichen Daten bereitstellen (in jeder Form) und weitere nutzende Personen für die Mitwirkung an ihrem Projekt in der durch die Funktionalitäten der Plattform ermöglichten Art und Weise anwerben. Die Mitarbeitenden des CCCS gehören nicht zu den Personen, die Projekte entwickeln.",
    "terms-list-item-5": "<b>Mitwirkende</b>: Die nutzenden Personen, die in der durch die Funktionalitäten der Plattform ermöglichten Art und Weise freiwillig an Projekten mitwirken. Mitwirkende können anonym bleiben oder auf freiwilliger Basis personenbezogene Daten über sich preisgeben, indem sie sich auf den Plattformen von CS Zürich registrieren.",

    "terms-text-1": "Die folgenden Nutzungsbedingungen gelten für alle nutzenden Personen, die die Plattformen von CS Zurich besuchen und/oder in irgendeiner Weise nutzen.",
    "terms-text-2": "Die projektentwickelnden Personen sind in vollem Umfang für die Erfüllung der Pflichten in Verbindung mit den von ihnen entwickelten Projekten und von ihnen hochgeladenen Daten (unabhängig von der Form der Daten) verantwortlich. Sie verpflichten sich, alle für die Projektinhalte geschuldeten Lizenzgebühren und sonstigen Beträge zu entrichten. Sie verpflichten sich zur Einholung urheberrechtlicher Genehmigungen und sind im Falle von Urheberrechtsverletzungen gegenüber der Urheberrechtsinhaberin oder Urheberrechtsinhaber schadenersatzpflichtig.",
    "terms-text-3": "Die Mitwirkenden sind die Eigentümerin oder der Eigentümer ihrer eigenen Beiträge und für dieses Eigentum verantwortlich. Soweit sie nicht Eigentümerin oder Eigentümer des Inhalts sind, müssen sie vor der Erbringung ihres Beitrags die Erlaubnis der Eigentümerin oder des Eigentümers einholen. ",
    "terms-text-4": "Die Mitwirkenden erteilen dem <b>CCCS</b> eine unbefristete, gebührenfreie und nicht ausschliessliche Lizenz zur Nutzung, Wiedergabe, Änderung und Ausübung aller Urheber- und Veröffentlichungsrechte in Bezug auf ihren Beitrag.",
    "terms-text-5": "Die Beiträge auf den Plattformen von CS Zürich stehen den projektentwickelnden Personen mit einer nicht ausschliesslichen Erlaubnis zur Nutzung, Verbreitung und Modifikation zur Verfügung, um die wissenschaftliche Forschung zu fördern.",
    "terms-text-6": "Das <b>CCCS</b> besitzt keinerlei Eigentumsrechte an den Inhalten, die die projektentwickelnden Personen auf die Plattformen von CS Zürich hochladen. Das <b>CCCS</b> kann nicht für Datenschutzpflichten, gesetzliche oder sonstige Pflichten in Verbindung mit den von den projektentwickelnden Personen auf die Plattformen von CS Zürich hochgeladenen Daten zur Verantwortung gezogen werden.",
    "terms-text-7": "Im Falle von Streitigkeiten zwischen den projektentwickelnden Personen und den Mitwirkenden ist das <b>CCCS</b> von Ansprüchen jeglicher Art freigestellt, die in irgendeiner Weise mit derartigen Streitigkeiten in Zusammenhang stehen.",
    "terms-text-8": "Das <b>CCCS</b> bestätigt Beiträge nicht und hat auch keine Kontrolle über sie. Es kann die Echtheit der Daten, die nutzende Personen bereitstellen, nicht garantieren und leistet keinerlei Garantien dafür, dass die Mitwirkenden ihren Beitrag leisten oder sich fair verhalten.",
    "terms-text-9": "CCCS behält sich insbesondere in Bezug auf den Citizen Science Project Builder ({lab}) vor, Inhalte und Projekte zu entfernen, wenn die Inhalte rechtswidrig sind oder bei Teilen des Projektpublikums Anstoss erregen könnten.",

    "research-heading":"Für die Forschungsdaten geltende Richtlinien",
    "research-text-1":"Die Generierung der Daten durch die auf den Plattformen von CS Zürich gehosteten Projekte erfolgt unter Beachtung der von der Europäischen Kommission im «FAIR Data Management Plan» gegebenen Empfehlung «{link-research}», der zufolge so wenige Einschränkungen wie möglich auferlegt, sensible Daten jedoch vor unbefugtem Zugriff geschützt werden sollen.",
    "research-text-2":"In allen Veröffentlichungen sollte mit folgendem Text auf das <b>CCCS</b> Bezug genommen werden: «Diese Publikation verwendet Daten, die über die Plattform des Citizen Science Center Zürich citizenscience.ch generiert wurden, einer gemeinsamen Initiative der Universität Zürich und der ETH Zürich.»",

    "privacy-heading": "Datenschutzerklärung",

    "privacy-text-1": "Alle Daten werden in Übereinstimmung mit dem Bundesgesetz über den Datenschutz (DSG) und der EU-Datenschutz-Grundverordnung (DSGVO) übermittelt. Alle Daten werden auf Servern innerhalb der Schweiz gespeichert",
    "privacy-text-2": "Bei der Registrierung auf der Plattform geben die nutzenden Personen eine E-Mail-Adresse an (Registrierung). Diese E-Mail-Adresse ist nicht sichtbar, und das CCCS wird E-Mail-Adressen oder personenbezogene Angaben niemals ausserhalb der Projekte weitergeben, denen eine nutzende Person ausdrücklich zugestimmt hat.",
    "privacy-text-3": "Das <b>CCCS</b> wird die E-Mail-Adresse der nutzenden Personen nur gelegentlich zur Ankündigung neuer Funktionen, neuer Projekte oder besonderer Ereignisse verwenden. Das <b>CCCS</b> kann die nutzenden Personen mit einem Newsletter über den Projektfortschritt oder die Aktivitäten des Centers informieren. Die nutzenden Personen können sich jederzeit abmelden, wenn sie diese Mitteilungen nicht mehr wünschen.",
    "privacy-text-4": "Das <b>CCCS</b> aggregiert allgemeine Statistiken über die Nutzung der Plattformen von CS Zürich. Dazu verwendet das <b>CCCS</b> Google Analytics, eine Software, die Daten sammelt, die mit der IP-Adresse der nutzenden Person in Verbindung stehen. Die von Google Analytics gesammelten Informationen werden gemäss der Datenschutzrichtlinie {policy} von Google Analytics behandelt.",
    "privacy-text-5": "Beim Zugriff auf einzelne CCCS-Seiten kommen möglicherweise temporäre Cookies zum Einsatz. Temporäre Cookies sind kleine Dateien, die von der Seite auf Ihrem Computer gespeichert werden, um eine optimale Nutzung der Website zu ermöglichen; die Cookies werden automatisch gelöscht, sobald der Webbrowser geschlossen wird. Sie können die Verwendung von temporären Cookies blockieren, indem Sie die Einstellungen in Ihrem Webbrowser entsprechend anpassen. Bitte beachten Sie, dass die Funktionalität der Webseiten von CCCS möglicherweise eingeschränkt ist, wenn Cookies ausgeschaltet, blockiert oder deaktiviert werden.",

    "help-text-1":"Bei weiteren Fragen zur Verwendung der Daten kontaktieren Sie bitte das <b>CCCS</b> unter folgender Anschrift:",
    "help-text-2":"Citizen Science Center Zürich",
    "help-text-3":"Kurvenstrasse 17",
    "help-text-4":"CH-8006 Zurich"

    }
    }
</i18n>
<template>
    <div>

        <app-content-section>

            <div class="content-wrapper">
                <div class="row row-centered scroll-effect">
                    <div class="col col-large-6">
                        <h2 class="heading centered" id="projects">{{ $t('terms-heading') }}</h2>
                        <p v-html="$t('terms-list-intro')" class="reduced-bottom-margin"></p>
                        <ul>
                            <li v-html="$t('terms-list-item-1')"></li>
                            <li v-html="$t('terms-list-item-2')"></li>
                            <li v-html="$t('terms-list-item-3')"></li>
                            <li v-html="$t('terms-list-item-4')"></li>
                            <li v-html="$t('terms-list-item-5')"></li>
                        </ul>
                        <p v-html="$t('terms-text-1')"></p>
                        <p v-html="$t('terms-text-2')"></p>
                        <p v-html="$t('terms-text-3')"></p>
                        <p v-html="$t('terms-text-4')"></p>
                        <p v-html="$t('terms-text-5')"></p>
                        <p v-html="$t('terms-text-6')"></p>
                        <p v-html="$t('terms-text-7')"></p>
                        <p v-html="$t('terms-text-8')"></p>
                        <p v-html="$t('terms-text-9',
                        {
                        'lab': `<a target='_blank' href='https://lab.citizenscience.ch'>https://lab.citizenscience.ch</a>`
                        })"></p>
                    </div>
                </div>
            </div>

        </app-content-section>

        <app-content-section color="light-greyish">

            <div class="content-wrapper">
                <div class="row row-centered scroll-effect">
                    <div class="col col-large-6">
                        <h2 class="heading centered" id="projects">{{ $t('research-heading') }}</h2>
                         <p v-html="$t('research-text-1',
                        {
                        'link-research': `<a target='_blank' href='https://ec.europa.eu/research/participants/docs/h2020-funding-guide/cross-cutting-issues/open-access-data-management/data-management_en.htm'>as open as possible, as closed as necessary</a>`
                        })"></p>
                        <p v-html="$t('research-text-2')"></p>
                    </div>
                </div>
            </div>
        </app-content-section>

        <app-content-section color="light-greyish">

            <div class="content-wrapper">
                <div class="row row-centered scroll-effect">
                    <div class="col col-large-6">
                        <h2 class="heading centered" id="projects">{{ $t('privacy-heading') }}</h2>
                        <p v-html="$t('privacy-text-1')"></p>
                        <p v-html="$t('privacy-text-2')"></p>
                        <p v-html="$t('privacy-text-3')"></p>
                         <p v-html="$t('privacy-text-4',
                        {
                        'policy': `<a target='_blank' href='https://policies.google.com/?hl=en-US'>Privacy Policy</a>`
                        })"></p>
                        <p v-html="$t('privacy-text-5')"></p>
                    </div>
                </div>
            </div>
        </app-content-section>

        
        <app-content-section >

            <div class="content-wrapper">
                <div class="row row-centered scroll-effect">
                    <div class="col col-large-6">
                        <span v-html="$t('help-text-1')"></span><br>
                        <span v-html="$t('help-text-2')"></span><br>
                        <span v-html="$t('help-text-3')"></span><br>
                        <span v-html="$t('help-text-4')"></span>
                    </div>
                </div>
            </div>
        </app-content-section>

        <section-newsletter-signup></section-newsletter-signup>

        <app-footer :platform="platform"></app-footer>

    </div>
</template>

<script>

    import ContentSection from '@/components/shared/ContentSection.vue'
    import Footer from '@/components/shared/Footer.vue'
    import SectionNewsletterSignup from "@/components/shared/SectionNewsletterSignup";

    export default {
        name: 'Terms',
        props: {
            platform: {
                type: Boolean,
                default: false
            }
        },
        components: {
            SectionNewsletterSignup,
            'app-content-section': ContentSection,
            'app-footer': Footer
        },
        metaInfo: function() {
            return {
                title: this.$t('page-title'),
                meta: [
                    {
                        property: 'og:title',
                        content: this.$t('page-title'),
                        template: '%s | '+this.$t('site-title')
                    }
                ]
            }
        }
    }

</script>

<style lang="scss">

</style>
